version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=your_database_url_here

networks:
  app-network:
    driver: bridge
